"use strict";

const { handlerName, emitStatement } = require("./emit");
const { generateRouteTable } = require("./route_table");
const { generateDispatch } = require("./dispatch_gen");

/**
 * Generate the complete C server source file from IR routes.
 *
 * @param {IRRoute[]} routes - All IR routes
 * @param {object} config - Build config (port, embed, etc.)
 * @param {string|null} assetsCode - Generated embedded assets C code, or null
 * @returns {string} - Complete C source file
 */
function generateServer(routes, config, assetsCode) {
  const lines = [];

  /* ---- Header ---- */
  lines.push("/*");
  lines.push(" * Auto-generated by cerver — do not edit.");
  lines.push(" */");
  lines.push("");
  lines.push('#include "cerver.h"');
  lines.push("");
  lines.push("#include <stdio.h>");
  lines.push("#include <stdlib.h>");
  lines.push("#include <string.h>");
  lines.push("");

  /* ---- Embedded assets (if any) ---- */
  if (assetsCode) {
    lines.push("/* ---- Embedded Assets ---- */");
    lines.push("");
    lines.push(assetsCode);
    lines.push("");
  } else {
    lines.push("/* No embedded assets */");
    lines.push("static cerver_asset_t *cerver_embedded_assets = NULL;");
    lines.push("static const int cerver_embedded_asset_count = 0;");
    lines.push("");
  }

  /* ---- Route table (forward decls + table) ---- */
  lines.push("/* ---- Routes ---- */");
  lines.push("");
  lines.push(generateRouteTable(routes));

  /* ---- Handler implementations ---- */
  lines.push("/* ---- Handler Implementations ---- */");
  lines.push("");

  for (const route of routes) {
    const name = handlerName(route.method, route.urlPath);
    lines.push(
      `static void ${name}(cerver_request_t *req, cerver_response_t *res) {`
    );

    /* Emit local variables */
    for (const v of route.handler.variables) {
      const varLines = emitStatement(v, 1);
      lines.push(...varLines);
    }

    /* Emit body statements */
    for (const stmt of route.handler.body) {
      const stmtLines = emitStatement(stmt, 1);
      lines.push(...stmtLines);
    }

    lines.push("}");
    lines.push("");
  }

  /* ---- Generated fast dispatch ---- */
  lines.push("/* ---- Generated Fast Dispatch (compile-time optimized) ---- */");
  lines.push("");
  lines.push(generateDispatch(routes));

  /* ---- Main function ---- */
  lines.push("/* ---- Entry Point ---- */");
  lines.push("");
  lines.push("int main(int argc, char *argv[]) {");
  lines.push("    (void)argc;");
  lines.push("    (void)argv;");
  lines.push("");
  lines.push(`    int port = ${config.port};`);
  lines.push("");
  lines.push("    /* Allow PORT env override */");
  lines.push('    const char *env_port = getenv("CERVER_PORT");');
  lines.push('    if (!env_port) env_port = getenv("PORT");');
  lines.push("    if (env_port) port = atoi(env_port);");
  lines.push("");
  lines.push("    cerver_server_t srv;");
  lines.push(`    cerver_init(&srv, port, ${config.threads});`);
  lines.push("");
  lines.push(
    "    cerver_add_routes(&srv, cerver_routes, cerver_route_count);"
  );
  lines.push("");

  /* Wire up generated dispatch */
  lines.push("    /* Use generated compile-time dispatch for fast routing */");
  lines.push("    cerver_set_dispatch(&srv, cerver_generated_dispatch);");
  lines.push("");

  if (assetsCode) {
    lines.push(
      "    cerver_set_assets(&srv, cerver_embedded_assets, cerver_embedded_asset_count);"
    );
  } else {
    lines.push('    cerver_set_public_dir(&srv, "./public");');
  }

  lines.push("");
  lines.push("    return cerver_listen(&srv);");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

module.exports = { generateServer };
