"use strict";

const { createEmitContext, handlerName, emitStatement } = require("./emit");
const { generateRouteTable } = require("./route_table");
const { generateDispatch } = require("./dispatch_gen");

/**
 * Generate server.c content.
 *
 * @param {object} config - Build config (port, threads, etc.)
 * @param {boolean} hasAssets - Whether embedding assets is enabled
 * @returns {string} - C source for server.c
 */
function generateServerC(config, hasAssets) {
  const lines = [];

  lines.push("/*");
  lines.push(" * Auto-generated by cerver — do not edit.");
  lines.push(" */");
  lines.push("");
  lines.push('#include "cerver.h"');
  lines.push("#include <stdio.h>");
  lines.push("#include <stdlib.h>");
  lines.push("");

  /* Routing externs */
  lines.push("/* Routing and Handler declarations */");
  lines.push("extern cerver_route_t cerver_routes[];");
  lines.push("extern const int cerver_route_count;");
  lines.push(
    "extern cerver_handler_fn cerver_generated_dispatch(cerver_request_t *req);",
  );
  lines.push("");

  /* Asset declarations */
  if (hasAssets) {
    lines.push("/* Embedded Assets */");
    lines.push("extern cerver_asset_t cerver_embedded_assets[];");
    lines.push("extern const int cerver_embedded_asset_count;");
    lines.push("");
  } else {
    lines.push("/* No embedded assets */");
    lines.push("");
  }

  /* Main function */
  lines.push("/* ---- Entry Point ---- */");
  lines.push("");
  lines.push("int main(int argc, char *argv[]) {");
  lines.push("    (void)argc;");
  lines.push("    (void)argv;");
  lines.push(`    int port = ${config.port};`);
  lines.push("");
  lines.push("    /* Allow PORT env override */");
  lines.push('    const char *env_port = getenv("CERVER_PORT");');
  lines.push('    if (!env_port) env_port = getenv("PORT");');
  lines.push("    if (env_port) port = atoi(env_port);");
  lines.push("");
  lines.push("    cerver_server_t srv;");
  lines.push(`    cerver_init(&srv, port, ${config.threads});`);
  lines.push("");
  lines.push("    cerver_add_routes(&srv, cerver_routes, cerver_route_count);");
  lines.push("");
  lines.push("    /* Use generated compile-time dispatch for fast routing */");
  lines.push("    cerver_set_dispatch(&srv, cerver_generated_dispatch);");
  lines.push("");
  if (hasAssets) {
    lines.push(
      "    cerver_set_assets(&srv, cerver_embedded_assets, cerver_embedded_asset_count);",
    );
  } else {
    lines.push('    cerver_set_public_dir(&srv, "./public");');
  }
  lines.push("");
  lines.push("    return cerver_listen(&srv);");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate routes.c content.
 *
 * @param {IRRoute[]} routes - All IR routes
 * @returns {string} - C source for routes.c
 */
function generateRoutesC(routes) {
  const lines = [];
  const emitCtx = createEmitContext();

  lines.push("/*");
  lines.push(" * Auto-generated route handler logic — do not edit.");
  lines.push(" */");
  lines.push("");
  lines.push('#include "cerver.h"');
  lines.push("#include <string.h>");
  lines.push("#include <stdlib.h>");
  lines.push("#include <stdio.h>");
  lines.push("");

  /* ---- Route table (forward decls + table) ---- */
  lines.push("/* ---- Routes ---- */");
  lines.push("");
  lines.push(generateRouteTable(routes));

  /* ---- Handler implementations ---- */
  lines.push("/* ---- Handler Implementations ---- */");
  lines.push("");

  for (const route of routes) {
    const name = handlerName(route.method, route.urlPath);
    emitCtx.ownedStrings = new Set();
    lines.push(
      `static void ${name}(cerver_request_t *req, cerver_response_t *res) {`,
    );

    /* Emit local variables */
    for (const v of route.handler.variables) {
      const varLines = emitStatement(v, 1, emitCtx);
      lines.push(...varLines);
    }

    /* Emit body statements */
    for (const stmt of route.handler.body) {
      const stmtLines = emitStatement(stmt, 1, emitCtx);
      lines.push(...stmtLines);
    }

    lines.push("}");
    lines.push("");
  }

  /* ---- Generated fast dispatch ---- */
  lines.push(
    "/* ---- Generated Fast Dispatch (compile-time optimized) ---- */",
  );
  lines.push("");
  lines.push(generateDispatch(routes));

  return lines.join("\n");
}

/**
 * Generate the complete C server source structures from IR routes.
 *
 * @param {IRRoute[]} routes - All IR routes
 * @param {object} config - Build config (port, embed, etc.)
 * @param {boolean} hasAssets - Whether embedding assets is enabled
 * @returns {{ serverC: string, routesC: string }} - Generated files object
 */
function generateServer(routes, config, hasAssets) {
  return {
    serverC: generateServerC(config, hasAssets),
    routesC: generateRoutesC(routes),
  };
}

module.exports = { generateServer, generateServerC, generateRoutesC };
